spring:
  application:
    name: white-bank-cmd

axon:
  serializer:
    general: jackson

server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka