spring:
  application:
    name: white-bank-gateway
  cloud:
    gateway:
      routes:
      - id: white-bank-cmd
        uri: lb://white-bank-cmd
        predicates:
        - Method=POST,PUT
      - id: white-bank-query
        uri: lb://white-bank-query
        predicates:
        - Method=GET

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka


