
spring:
  application:
    name: white-bank-query
  data:
    mongodb:
      uri: mongodb+srv://whitebank:whitebank@whitebank.ypzuf9p.mongodb.net/whitebankquery?retryWrites=true&w=majority

server:
  port: 8082

axon:
  serializer:
    messages: jackson

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka